language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install setuptools twine
  - pip install -r requirements.txt

install:
  - python unittests.py
  - python pytest.py

script:
  - python setup.py sdist
  - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing
